// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADRso4xREWUzHDFowyR7h2jTm_pCL36NY',
    appId: '1:534417534017:web:2cdb3d208f04e1bdd52ac0',
    messagingSenderId: '534417534017',
    projectId: 'crudtutorial-8a3b6',
    authDomain: 'crudtutorial-8a3b6.firebaseapp.com',
    storageBucket: 'crudtutorial-8a3b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALPz4mu2rw98usxqkW1wzMrL2qt1VHwWk',
    appId: '1:534417534017:android:db04e73ba2ae061dd52ac0',
    messagingSenderId: '534417534017',
    projectId: 'crudtutorial-8a3b6',
    storageBucket: 'crudtutorial-8a3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk0Bm3qKdEFnmodI7JfXSGWzzjaU75FpU',
    appId: '1:534417534017:ios:20ae4235788155b0d52ac0',
    messagingSenderId: '534417534017',
    projectId: 'crudtutorial-8a3b6',
    storageBucket: 'crudtutorial-8a3b6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk0Bm3qKdEFnmodI7JfXSGWzzjaU75FpU',
    appId: '1:534417534017:ios:20ae4235788155b0d52ac0',
    messagingSenderId: '534417534017',
    projectId: 'crudtutorial-8a3b6',
    storageBucket: 'crudtutorial-8a3b6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADRso4xREWUzHDFowyR7h2jTm_pCL36NY',
    appId: '1:534417534017:web:60766b926b9a5a22d52ac0',
    messagingSenderId: '534417534017',
    projectId: 'crudtutorial-8a3b6',
    authDomain: 'crudtutorial-8a3b6.firebaseapp.com',
    storageBucket: 'crudtutorial-8a3b6.appspot.com',
  );
}
